#%RAML 0.8
title: Todo App API document
baseUri: http://localhost:8080
version: v1

securitySchemes:
  - BasicAuth:
      type: Basic Authentication

traits:
  - unsecured:
      description: no need Basic Auth
  - secured:
      description: need Basic Auth
  - admin:
      description: admin which means admin flag is true
  - owner:
      description: the owner of the item

/todos:
  get:
    description: return all todo items in a list
    is: [unsecured]
    queryParameters:
      who:
        description: the name to be filtered
        type: string
        required: false
        example: xiaoming
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                  "id": 1,
                  "title": "sample title with id 1",
                  "who": "xiaoming",
                  "updatedDatetime": "2016-07-13 17:00:00",
                  "createdDatetime": "2016-07-13 17:00:00"
                },
                {
                  "id": 2,
                  "title": "sample title with id 2",
                  "who": "meimei",
                  "updatedDatetime": "2016-07-15 11:10:00",
                  "createdDatetime": "2016-07-15 11:00:00"
                }
              ]
  post:
    description: create a new todo item
    is: [secured]
    securedBy: BasicAuth
    body:
      application/json:
        formParameters:
          title:
            description: the title of the item to be added
            type: string
            required: true
            example: the title of the new item
          summary:
            description: the summary of the item to be added
            type: string
            required: true
            example: the summary of the new item
          username:
            description: the username
            required: true
            type: string
            example: xiaoming
          password:
            description: the password
            required: true
            type: string
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": 1,
                "title": "the title for the new todo item",
                "summary": "the summary for the new todo item",
                "who": "xiaoming",
                "createdDatetime": "2016-07-01 17:00:00",
                "updatedDatetime": "2016-07-01 17:00:00"
              }
      400:
        body:
          application/json:
            example: |
              {
                "message": "title shouldn't be empty."
              }
      401:
        body:
          application/json:
            example: |
              {
                "message": "your username or password is wrong."
              }

/todos/{itemId}:
  uriParameters:
    itemId:
      description: the item id
      type: integer
      required: true
  get:
    description: retrieve one item by given item id
    is: [unsecured]
    responses:
      200:
        description: successfully find a created item
        body:
          application/json:
            example: |
              {
                "id": 1,
                "title": "the title for the new todo item",
                "summary": "the summary for the new todo item",
                "who": "xiaoming",
                "createdDatetime": "2016-07-01 17:00:00",
                "updatedDatetime": "2016-07-01 17:00:00"
              }
      400:
        description: can't find any item by given item id
        body:
          application/json:
            example: |
              {
                "message": "can't find the item with the given item id"
              }
  put:
    description: update existing item
    is: [secured, owner, admin]
    securedBy: BasicAuth
    body:
      application/json:
        formParameters:
          id:
            description: id of the item
            type: integer
            required: true
          title:
            description: the title of the item to be added
            type: string
            required: true
            example: the title of the new item
          summary:
            description: the summary of the item to be added
            type: string
            required: true
            example: the summary of the new item
          username:
            description: the username
            required: true
            type: string
          password:
            description: the password
            required: true
            type: string
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "id": 1,
                "title": "the title for the updated todo item",
                "summary": "the summary for the updated todo item",
                "who": "xiaoming",
                "createdDatetime": "2016-07-01 17:10:00",
                "updatedDatetime": "2016-07-01 17:00:00"
              }
      400:
        body:
          application/json:
            example: |
              {
                "message": "title shouldn't be empty."
              }
      401:
        body:
          application/json:
            example: |
              {
                "message": "your username or password is wrong."
              }
  delete:
    description: remove an item
    is: [secured, owner, admin]
    securedBy: BasicAuth
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message": "item has been removed successfully."
              }
      400:
        body:
          application/json:
            example: |
              {
                "message": "wrong item id."
              }
      401:
        body:
          application/json:
            example: |
              {
                "message": "unauthorized."
              }
